### ISSUE TITLE
Polyversal 2.0.0 returns '/usr/bin/env: ‘bash\r’: No such file or directory'

### ISSUE THREAD

**Issue by KBD20** [CommitteeOfZero/polyversal-coz-linux-patcher#20] opened 2023-08-25 06:48 UTC
The current version of Polyversal returns `/usr/bin/env: ‘bash\r’: No such file or directory` when I run ./polyversal.
Modifying it with `sed $'s/\r$//' ./polyversal > polyversal2` giving the new file run permission and using `./polyversal2` instead seems to work and the gui ran fine.

I don't know if this is a proper solution or not with this script, or if it was a mistake with this version.

**Comment by KBD20** [comment] 2023-08-25 06:53
For extra info I'm running `6.4.11-arch2-1` (EndeavourOS) on `bash 5.1.16`

**Comment by Macitron** [comment] 2023-08-27 23:26
Confirmed, it looks like the download files somehow had their line endings converted from Unix to DOS. The shebang line ends with `bash\r\n`, so the CLI is trying to look for `bash\r` to execute. I'll follow up and see if we can get that fixed

**Comment by Mafu0567** [comment] 2023-08-29 16:07
Yeah cloning the repo or downloading the zip repo seems to work fine also.
Tested on Steam Deck with SteamOS Version `3.4.8`

**Comment by Macitron** [comment] 2023-08-30 05:17
Fixed now, release downloads are working fine :)

**Closed** 2023-09-15 08:11 UTC
